Repository tallysdev/dotL0V3, pull requests merged in 2023-12, with the labels that each got.

#6 Criação de Home Page
  frontend/src/app/page.tsx
Labels: enhancement

#7 Criação de footer e header
  frontend/.editorconfig
  frontend/public/github.svg
  frontend/public/heart.svg
  frontend/public/linkedin.svg
  frontend/public/logo.svg
  frontend/public/x.svg
  frontend/src/app/components/footer.tsx
  frontend/src/app/components/navbar.tsx
  frontend/src/app/layout.tsx
Labels: enhancement

#9 build(init): updating files to host backend
  backend/Dockerfile
  backend/docker-compose.yml
  backend/package.json
Labels: enhancement

#15 add cors
  backend/package.json
  backend/src/server.ts
Labels: bug

#17 Feat/8 user info
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/user/[id]/components/user_page.tsx
  frontend/src/app/user/[id]/page.tsx
  frontend/src/app/user/page.tsx
Labels: enhancement

#18 Feat/4 login page
  frontend/src/app/components/navbar.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/app/user/[id]/components/user_page.tsx
  frontend/src/app/user/[id]/page.tsx
Labels: bug, enhancement

#19 feat(feed): add user feed and necessary packages
  frontend/package-lock.json
  frontend/package.json
  frontend/public/fabricio.jpg
  frontend/src/app/components/userCard.tsx
  frontend/src/app/feed/components/userCarousel.tsx
  frontend/src/app/feed/page.tsx
  frontend/types/index.d.ts
Labels: enhancement
